config/routes.rb
Rails.application.routes.draw do
 
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  #Devise user
  devise_for :users

  #Routes acces
  root to: "home#index"
  
  #Json fromat routes
  namespace :api do
    namespace :v1 do
      resources :users,       only: [:show]
      resources :payments,    only: [:index]
      resources :groups,      only: [:index]
      resources :settings,    only: [:index]
      resources :promotions,  only: [:index]
    end
   end

  #All ressources pages
  resources :users,       only: [:show]
  resources :payments,    only: [:index]
  resources :groups,      only: [:index]
  resources :settings,    only: [:index]
  resources :promotions,  only: [:index]

  #All ressources admin pages
  namespace :admin do
    resources :users do
      collection do
        post :confirm
      end
    end

    resources :groups do
      collection do
        post :confirm
      end
    end

    resources :promotions do
      collection do
        post :confirm
      end
    end

    resources :payments do
      collection do
        post :confirm
      end
    end

    resources :settings do
      collection do
        post :confirm
      end
    end
  end

end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :users

  validates :name, presence: true, uniqueness: true

  validates :description, presence: true

  validates :year_promotion, presence: true 

  mount_uploader :image_promotion, ImagePromotionUploader

  paginates_per 5

  def image_promotion_thumbnail
    if avatar.present?
      avatar.url
    else
      '/image.png'
    end
  end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < ApplicationController
  before_action :set_promotion, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin!

  def index
    @user = User.all
    @promotions = Promotion.all.order('created_at DESC').page params[:page]
  end

  def new
    @promotion = Promotion.new
  end

  def edit
    @promotion = Promotion.find(params[:id])
  end
  

  def show 
    @promotion = Promotion.find(params[:id])
  end
  

  def create
    @promotion = Promotion.new(promotion_params)
    if @promotion.save
      redirect_to admin_promotions_path, notice: "Promotion enregistrée avec succès!"
    else
      render :new
    end
  end

  def update
    if @promotion.update(promotion_params)
      redirect_to admin_promotions_path, notice: "Promotion mise à jour avec succès!"
    else
      render :edit 
    end
  end

  def destroy
    @promotion.destroy
    redirect_to admin_promotions_path, notice: "Promotion supprimée avec succès!"
  end
  
  private 
  def authenticate_admin! 
    unless current_user.admin?
      flash[:info] = "Vous n'avez pas les privilèges pour accéder à cette page."
      redirect_to root_path
    end
  end

  def promotion_params
    params.require(:promotion).permit(:name, :description, :year_promotion, :image_promotion, :image_promotion_cache, :user_id)
  end

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end
  
end

app/controllers/api/v1/promotions_controller.rb
class Api::V1::PromotionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]  
  before_action :set_promotion, only: %i[index]

  def index
    @user = User.all
    @promotions = Promotion.all 
    render json: @promotions
  end

  private 
  def promotion_params
    params.permit(:name, :description, :year_promotion, :image_promotion, :user_id)
  end 
  def set_promotion
    @promotion = Promotion.find_by(params[:id])
  end
end

app/controllers/promotion_controller.rb
class PromotionController < ApplicationController
  before_action :authenticate_user!, except: %i[index]  
  before_action :set_promotion, only: %i[index]

  def index
    @user = User.all
    @promotions = Promotion.all 
  end

  private 
  def promotion_params
    params.permit(:name, :description, :user_id)
  end 
  def set_promotion
    @group = Group.find_by(params[:id])
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]  
  before_action :set_promotion, only: %i[index]

  def index
    @user = User.all
    @promotions = Promotion.all 
  end

  private 
  def promotion_params
    params.permit(:name, :description, :year_promotion, :image_promotion, :image_promotion_cache, :user_id)
  end 
  def set_promotion
    @promotion = Promotion.find_by(params[:id])
  end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/admin/promotions/_form.html.erb
<div id="main" class="container">
  <div id="error_explanation">  
    <% if @promotion.errors.any? %>
      <div id="error_explanation">
        <h4>
        <%= pluralize(@promotion.errors.count, "error") %> prohibited
        this promotion from being saved:
        </h4>
        <ul>
        <% @promotion.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger">
            <li><%= msg %></li>
          </div>
        <% end %>
        </ul>
      </div>  
    <% end %>
  </div> 
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with(model: @promotions, url: admin_promotions_path, local: true) do |f| %> 
        <div class="form-group">
          <label class="mb-1"><span>Add photo</span></label>
          <%= f.file_field :image_promotion, autofocus: true, accept:"image/*", autocomplete: "image_promotion",class:"form-control"%>
          <%= f.hidden_field :image_promotion_cache %>
        </div> 
        <div class="form-group">
          <label class="mb-1"><strong>Année</strong></label>
            <%= f.date_field :year_promotion, autofocus: true, autocomplete: "year_promotion", class:"form-control", placeholder:"Promotion year", :required=> true%>
        </div> 
        <div class="form-group">
          <label class="mb-1"><strong>Nom</strong></label>
            <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"Promotion name", :required=> true%>
        </div> 
        <div class="form-group">
          <label class="mb-1"><strong>Description</strong></label>
          <%= f.text_area :description, autofocus: true, autocomplete: "description", class:"form-control", placeholder:"Promotion description", :required=> true%>
        </div> 
        <div class="text-center mb-2">
          <%= f.submit "Valider", :class => "btn btn-primary"%>
          <%= link_to  "Retour", admin_promotions_path, :class => "btn btn-secondary" %> 
        </div>  
      <% end %>
    </div>
  </div>
</div>

app/views/admin/promotions/edit.html.erb
<div id="main" class="container">
  <div id="error_explanation">  
    <% if @promotion.errors.any? %>
      <div id="error_explanation">
        <h4>
        <%= pluralize(@promotion.errors.count, "error") %> prohibited
        this promotion from being saved:
        </h4>
        <ul>
        <% @promotion.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger">
            <li><%= msg %></li>
          </div>
        <% end %>
        </ul>
      </div>  
    <% end %>
  </div> 
  <div class="row">
    <div class="col-6 mx-auto">
    <h4 class="py-5 fw-normal fs-3 text-uppercase text-center"> Modification</h4>
      <%= form_with(model: @promotions, url: admin_promotion_path, local: true) do |f| %> 
        <div class="form-group">
          <label class="mb-1"><span>Add photo</span></label>
          <%= f.file_field :image_promotion, autofocus: true, accept:"image/*", autocomplete: "image_promotion",class:"form-control"%>
          <%= f.hidden_field :image_promotion_cache %>
        </div> 
        <div class="form-group">
          <label class="mb-1"><strong>Année</strong></label>
            <%= f.date_field :year_promotion, autofocus: true, autocomplete: "year_promotion", class:"form-control", placeholder:"Promotion year", :required=> true%>
        </div> 
        <div class="form-group">
          <label class="mb-1"><strong>Nom</strong></label>
            <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"Promotion name", :required=> true%>
        </div> 
        <div class="form-group">
          <label class="mb-1"><strong>Description</strong></label>
          <%= f.text_area :description, autofocus: true, autocomplete: "description", class:"form-control", placeholder:"Promotion description", :required=> true%>
        </div> 
        <div class="text-center mb-2">
          <%= f.submit "Valider", :class => "btn btn-primary"%>
          <%= link_to  "Retour", admin_promotions_path, :class => "btn btn-secondary" %> 
        </div>  
      <% end %>
    </div>
  </div>
</div>

app/views/admin/promotions/index.html.erb
<div id="main" class="container py-11">
  <div class="row">
      <div class="col-12">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
          <!--<p><%= notice%></p> -->
        <% end %>
      </div>
    </div>
    <%if current_user.admin%> 
    <div class="row">
      <div class="col-12 text-center"> 
        <h5 class="py-4 fw-normal text-uppercase">Informations des promotions</h5>
        <table class="table table-borderless">
          <thead class="table-primary">
            <tr class="fs-1 fw-bold">
              <th>Image</th>
              <th>Année</th>
              <th>Nom</th>
              <th>Description</th>
              <th>Nombre d'utilisateur ajouté</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @promotions.each do |promotion| %>
              <tr>
                <td>
                  <%#= image_tag (promotion.image_promotion_thumbnail), style: 'height:150px;width:150px;'%>
                  <%= link_to promotion.image_promotion_url do %>
                    <%= image_tag promotion.image_promotion_url, class: "thumbnail", style: 'height:60px;width:60px;' %>
                  <% end %>
                </td>
                <td><%= promotion.year_promotion%> </td>
                <td><%= promotion.name%></td>
                <td><%= promotion.description%></td>
                <td>
                  <%= promotion.users.count%>
                </td> 
                <td>
                  <%= link_to fa_icon('eye', text: "Voir"), promotions_path(promotion.id), class: "btn btn-outline-primary btn-sm" %>
                  <%= link_to fa_icon('edit', text: "Modifier"), edit_admin_promotion_path(promotion),:class=>"btn btn-outline-secondary btn-sm" %>
                  <%= link_to fa_icon('trash', text: "Supprimer"), admin_promotion_path(promotion), method: :delete, data: { confirm: 'are you sure ?' },:class=>"btn btn-outline-danger btn-sm" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>  
      </div>
      <%= link_to fa_icon('plus', text: "Ajouter une promotion"), new_admin_promotion_path, class: "btn btn-outline-primary btn-sm col-3 mx-auto" %>
    </div> 
    <%end%> 
  <%= paginate @promotions%>
</div>

app/views/admin/promotions/new.html.erb
<div class="container">
  <h4 class="py-5 fw-normal fs-3 text-uppercase text-center"> Nouvelle promotion</h4>
  <%= render 'form', promotion: @promotion %>
</div>

app/views/admin/promotions/show.html.erb
<div id="main" class="container">
  <h5 class="fw-normal text-uppercase"> La promotion</h5>
  <table class="table table-borderless">
    <thead class="table-primary">
      <tr class="fs-1 fw-bold">
        <th>Image</th>
        <th>Année</th>
        <th>Nom</th> 
        <th>Description</th> 
        <th>Action</th>
      </tr>
    </thead> 
    <tbody>
      <tr>
        <td><%= image_tag (@promotion.image_promotion_thumbnail), style: 'height:70px;width:70px;'%></td>
        <td><%= @promotion.year_promotion%> </td> 
        <td><%= @promotion.name %></td>
        <td><%= @promotion.description %></td> 
        <td>
          <%= link_to fa_icon('back', text: "Retour"), admin_promotions_path, class: "btn btn-secondary btn-sm" %>
          <%= link_to "Modifier", edit_admin_promotion_path(@promotion), class: "btn btn-secondary btn-sm" %>
          <%= link_to "Supprimer", admin_promotion_path(@promotion.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-secondary btn-sm"%> 
        </td>
      </tr>
    </tbody>  
  </table>
</div>