config/routes.rb
Rails.application.routes.draw do
 
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  #Devise user
  devise_for :users

  #Routes acces
  root to: "home#index"
  
  #Json fromat routes
  namespace :api do
    namespace :v1 do
      resources :users,       only: [:show]
      resources :payments,    only: [:index]
      resources :groups,      only: [:index]
      resources :settings,    only: [:index]
      resources :promotions,  only: [:index]
    end
   end

  #All ressources pages
  resources :users,       only: [:show]
  resources :payments,    only: [:index]
  resources :groups,      only: [:index]
  resources :settings,    only: [:index]
  resources :promotions,  only: [:index]

  #All ressources admin pages
  namespace :admin do
    resources :users do
      collection do
        post :confirm
      end
    end

    resources :groups do
      collection do
        post :confirm
      end
    end

    resources :promotions do
      collection do
        post :confirm
      end
    end

    resources :payments do
      collection do
        post :confirm
      end
    end

    resources :settings do
      collection do
        post :confirm
      end
    end
  end

end

app/models/setting.rb
class Setting < ApplicationRecord
  has_many :users

  validates :amount_due, presence: true

  validates :devise, presence: true
  
  paginates_per 5
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_action :set_setting, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin!

  def index
    @user = User.all
    @settings = Setting.all.order('created_at DESC').page params[:page]
  end

  def new
    @setting = Setting.new
  end

  def edit
    @setting = Setting.find(params[:id])
  end

  def show 
    @setting = Setting.find(params[:id])
  end

  def create
    @setting = Setting.new(setting_params)
    if @setting.save
      redirect_to admin_settings_path, notice: "Paramètre enregistré!"
    else
      render :new
    end
  end

  def update
    if @setting.update(setting_params)
      redirect_to admin_settings_path, notice: "Paramètre mise à jour avec succès!"
    else
      render :edit 
    end
  end

  def destroy
    @setting.destroy
    redirect_to admin_settings_path, notice: "Paramètre supprimé avec succès!"
  end
  
  private 
  def authenticate_admin! 
    unless current_user.admin?
      flash[:info] = "Vous n'avez pas les privilèges pour accéder à cette page."
      redirect_to root_path
    end
  end

  def setting_params
    params.require(:setting).permit(:amount_due, :devise, :user_id)
  end

  def set_setting
    @setting = Setting.find(params[:id])
  end
end

app/controllers/api/v1/settings_controller.rb
class Api::V1::SettingsController < ApplicationController
  before_action :set_setting, only: %i[index]
  before_action :authenticate_user! 
  def index
    @user = User.all
    @settings = Setting.all
    render json: @settings
  end

  def show 
    @setting = Setting.find(params[:id])
  end

  private
  def setting_params
    params.permit(:amount_due, :devise, :user_id)
  end 

  def set_setting
    @setting = Setting.find_by(params[:id])
  end
 
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[index]
  before_action :authenticate_user! 
  def index
    @user = User.all
    @settings = Setting.all
  end

  private
  def setting_params
    params.permit(:amount_due, :devise, :user_id)
  end 

  def set_setting
    @setting = Setting.find_by(params[:id])
  end
 
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/admin/settings/_form.html.erb
<div id="main"  id="error_explanation">  
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h4>
      <%= pluralize(@setting.errors.count, "error") %> prohibited
      this setting from being saved:
      </h4>
      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger">
          <li><%= msg %></li>
        </div>
      <% end %>
      </ul>
    </div>  
  <% end %>
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with(model: @setting, url: admin_settings_path, local: true) do |f| %>
        <div class="field form-goup">
          <%= f.label :Devise %>
          <%= f.text_field :devise, :class => 'form-control'%> 
        </div> 
        <div class="field form-goup py-2">
          <%= f.label :Montant %>
          <%= f.number_field :amount_due, :class => 'form-control' %> 
        </div> 
        <div class="text-center mb-2 py-2">
          <%= f.submit "Valider", :class => "btn btn-primary"%>
          <%= link_to  "Retour", admin_settings_path, :class => "btn btn-secondary" %> 
        </div> 
      <% end %>
    </div>
  </div>
</div>

app/views/admin/settings/edit.html.erb
<div id="main"  id="error_explanation">  
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h4>
      <%= pluralize(@setting.errors.count, "error") %> prohibited
      this setting from being saved:
      </h4>
      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger">
          <li><%= msg %></li>
        </div>
      <% end %>
      </ul>
    </div>  
  <% end %> 
  <div class="row">
    <div class="col-6 mx-auto">
      <h4 class="py-5 fw-normal fs-3 text-uppercase text-center"> Modification</h4>
      <%= form_with(model: @setting, url: admin_setting_path, local: true) do |f| %> 
        <div class="field form-goup">
          <%= f.label :Devise %>
          <%= f.text_field :devise, :class => 'form-control' %> 
        </div> 
        <div class="field form-goup py-2">
          <%= f.label :Amount %>
          <%= f.number_field :amount_due, :class => 'form-control' %> 
        </div> 
        <div class="text-center mb-2 py-2">
          <%= f.submit "Mise à jour", :class => "btn btn-primary"%>
          <%= link_to  "Retour", admin_settings_path, :class => "btn btn-secondary" %> 
        </div> 
      <% end %>
    </div>
  </div>
</div>

app/views/admin/settings/index.html.erb
<div id="main" class="container">
  <div class="row">
    <div class="col-12">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
          <!--<p><%= notice%></p> -->
      <% end %>
    </div>
  </div> 
  <div class="row">
    <div class="col-12 text-center"> 
      <h5 class="fw-normal text-uppercase py-5"> Information sur les paramètres</h5>
      <table class="table table-borderless">
        <thead class="table-primary">
            <tr class="fs-1 fw-bold text-center">
              <th>La Devise</th> 
              <th>Montant</th>
              <th>Action</th>
            </tr>
        </thead>
        <tbody>
          <% @settings.each do |setting| %>
              <tr class="text-center">            
                <td><%= setting.devise%></td>
                <td><%= setting.amount_due%> </td> 
                <td>  
                  <%= link_to fa_icon('eye', text: "Voir"), settings_path(setting.id), class: "btn btn-outline-primary btn-sm" %>
                  <%= link_to fa_icon('edit', text: "Modifier"), edit_admin_setting_path(setting),:class=>"btn btn-outline-secondary btn-sm" %>
                  <%= link_to fa_icon('trash', text: "Supprimer"), admin_setting_path(setting), method: :delete, data: { confirm: 'are you sure ?' },:class=>"btn btn-outline-danger btn-sm" %>
                </td>
              </tr>
          <% end %>
        </tbody> 
      </table>
    </div>
    <%= link_to fa_icon('plus', text: "Ajouter un paramètre"), new_admin_setting_path, class: "btn btn-outline-primary btn-sm col-3 mx-auto" %>
  </div>  
  <%= paginate @settings%>
</div>

app/views/admin/settings/new.html.erb
<div class="container">
  <h4 class="py-5 fw-normal fs-3 text-uppercase text-center"> Nouveau paramètre</h4>
  <%= render 'form', setting: @setting %>
</div>

app/views/admin/settings/show.html.erb
<div id="main" class="container">
  <h5 class="fw-normal text-uppercase"> Le paramètre</h5>
  <table class="table table-borderless">
    <thead class="table-primary">
      <tr class="fs-1 fw-bold">
        <th>Montant</th> 
        <th>Devise</th> 
        <th>Action</th>
      </tr>
    </thead> 
    <tbody>
      <tr> 
        <td><%= @setting.amount_due%></td>
        <td><%= @setting.devise %></td> 
        <td>
          <%= link_to "Retour", admin_settings_path, class: "btn btn-secondary" %>
          <%= link_to "Modifier", edit_admin_setting_path(@setting), class: "btn btn-secondary" %>
          <%= link_to "Supprimer", admin_setting_path(@setting.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-secondary"%> 
        </td>
      </tr>
    </tbody>  
  </table>
</div>