config/routes.rb
Rails.application.routes.draw do
 
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  #Devise user
  devise_for :users

  #Routes acces
  root to: "home#index"
  
  #Json fromat routes
  namespace :api do
    namespace :v1 do
      resources :users,       only: [:show]
      resources :payments,    only: [:index]
      resources :groups,      only: [:index]
      resources :settings,    only: [:index]
      resources :promotions,  only: [:index]
    end
   end

  #All ressources pages
  resources :users,       only: [:show]
  resources :payments,    only: [:index]
  resources :groups,      only: [:index]
  resources :settings,    only: [:index]
  resources :promotions,  only: [:index]

  #All ressources admin pages
  namespace :admin do
    resources :users do
      collection do
        post :confirm
      end
    end

    resources :groups do
      collection do
        post :confirm
      end
    end

    resources :promotions do
      collection do
        post :confirm
      end
    end

    resources :payments do
      collection do
        post :confirm
      end
    end

    resources :settings do
      collection do
        post :confirm
      end
    end
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users

  validates :name, presence: true, uniqueness: true

  validates :description, presence: true

  paginates_per 5
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authenticate_admin!

  def index
    @user = User.all
    @groups = Group.all.order('created_at DESC').page params[:page]
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end
  

  def show 
    @group = Group.find(params[:id])
  end
  

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to admin_groups_path, notice: "Groupe créé avec succès!"
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to admin_groups_path, notice: "Groupe mise à jour avec succès!"
    else
      render :edit 
    end
  end

  def destroy
    @group.destroy
    redirect_to admin_groups_path, notice: "Groupe supprimé avec succès!"
  end
  
  private 
  def authenticate_admin! 
    unless current_user.admin?
      flash[:info] = "Vous n'avez pas les privilèges pour accéder à cette page."
      redirect_to root_path
    end
  end

  def group_params
    params.require(:group).permit(:name, :description, :user_id)
  end

  def set_group
    @group = Group.find(params[:id])
  end
  
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApplicationController  
  before_action :authenticate_user!, except: %i[index]  
  before_action :set_group, only: %i[index]

  def index
    @user = User.all
    @groups = Group.all
    render json: @groups 
  end

  private 
  def group_params
    params.permit(:name, :description, :user_id)
  end 
  def set_group
    @group = Group.find_by(params[:id])
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController  
  before_action :authenticate_user!, except: %i[index]  
  before_action :set_group, only: %i[index]

  def index
    @user = User.all
    @groups = Group.all 
  end

  private 
  def group_params
    params.permit(:name, :description, :user_id)
  end 
  def set_group
    @group = Group.find_by(params[:id])
  end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/admin/groups/_form.html.erb
<div id="main" class="container">
  <div id="error_explanation">  
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h4>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group from being saved:
        </h4>
        <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger">
            <li><%= msg %></li>
          </div>
        <% end %>
        </ul>
      </div>  
    <% end %>
  </div>  
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with(model: @group, url: admin_groups_path, local: true) do |f| %> 
        <div class="form-inputs">
          <div class="form-group">
            <label class="mb-1"><strong>Nom</strong></label>
              <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"Group name", :required=> true%>
          </div> 
          <div class="form-group py-2">
            <label class="mb-1"><strong>Description</strong></label>
            <%= f.text_area :description, autofocus: true, autocomplete: "description", class:"form-control", placeholder:"Group description", :required=> true%>
          </div> 
          <div class="text-center mb-2 py-3">
            <%= f.submit "Valider", :class => "btn btn-outline-primary btn-sm"%>
            <%= link_to fa_icon('arrow-left', text: "Retour"), admin_groups_path, :class => "btn btn-outline-secondary btn-sm" %> 
          </div>
        </div>  
      <% end %>
    </div>
  </div>
</div>

app/views/admin/groups/edit.html.erb
<div id="main" class="container">
  <div id="error_explanation">  
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h4>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group from being saved:
        </h4>
        <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger">
            <li><%= msg %></li>
          </div>
        <% end %>
        </ul>
      </div>  
    <% end %>
  </div>  
  <div class="row">
    <div class="col-6 mx-auto">
    <h4 class="py-5 fw-normal fs-3 text-uppercase text-center"> Modification</h4>
      <%= form_with(model: @group, url: admin_group_path, local: true) do |f| %> 
        <div class="form-inputs">
          <div class="form-group">
            <label class="mb-1"><strong>Nom</strong></label>
              <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"Group name", :required=> true%>
          </div> 
          <div class="form-group py-2">
            <label class="mb-1"><strong>Description</strong></label>
            <%= f.text_area :description, autofocus: true, autocomplete: "description", class:"form-control", placeholder:"Group description", :required=> true%>
          </div> 
          <div class="text-center mb-2 py-3">
            <%= f.submit "Mise à jour", :class => "btn btn-outline-primary btn-sm"%>
            <%= link_to fa_icon('arrow-left', text: "Retour"), admin_groups_path, :class => "btn btn-outline-secondary btn-sm" %> 
          </div>
        </div>  
      <% end %>
    </div>
  </div>
</div>


app/views/admin/groups/index.html.erb
<div id="main" class="container py-4 text-center">
  <div class="row">
      <div class="col-12">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
          <!--<p><%= notice%></p> -->
        <% end %>
      </div>
    </div>
   <%if current_user.admin%> 
      <div class="row">
        <div class="col-12"> 
          <h5 class=" fw-normal text-uppercase py-8">Information des groupes</h5>
          <table class="table table-borderless"> 
            <thead class="table-primary">
              <tr class="fs-1 fw-bold">
                <th>Name</th>
                <th>Description</th>
                <th>Nombre d'utilisateur ajoutés</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @groups.each do |group| %>
                <tr>
                  <td><%= group.name%> </td>
                  <td><%= group.description%></td>
                  <td>
                    <%= group.users.count%>
                  </td> 
                  <td> 
                    <%= link_to fa_icon('eye', text: "Voir"), groups_path(group.id), class: "btn btn-outline-primary btn-sm" %>
                    <%= link_to fa_icon('edit', text: "Modifier"), edit_admin_group_path(group),:class=>"btn btn-outline-secondary btn-sm" %>
                    <%= link_to fa_icon('trash', text: "Supprimer"), admin_group_path(group), method: :delete, data: { confirm: 'are you sure ?' },:class=>"btn btn-outline-danger btn-sm" %>
                  </td>
                </tr>
              <% end %>
            </tbody>  
          </table>  
        </div>
        <%= link_to fa_icon('plus', text: "Ajouter un groupe"), new_admin_group_path, class: "btn btn-outline-primary btn-sm col-3 mx-auto" %>
      </div> 
    <%end%>  
 <%= paginate @groups%>
</div>

app/views/admin/groups/new.html.erb
<div class="container">
  <h5 class="py-4 text-center fw-normal text-uppercase">Nouveau groupe</h5>
  <%= render 'form', group: @group %>
</div>

app/views/admin/groups/show.html.erb
<div id="main" class="container"> 
  <h5 class=" text-center py-4 fw-normal text-uppercase">Information du groupe </h5>
  <table class="table table-borderless"> 
    <thead class="table-primary">
      <tr class="fs-1 fw-bold text-center">
        <th>Name</th> 
        <th>Description</th>
        <th>nombre d'utilisateur ajoutés</th> 
        <th>Action</th>
      </tr>
    </thead> 
    <tbody>
      <tr class="fs-1 fw-bold text-center"> 
        <td><%= @group.name %></td>
        <td><%= @group.description %></td> 
        <td><%= @group.users.count %></td>
        <td>
          <%= link_to fa_icon('arrow-left', text: "Retour"), admin_groups_path, class: "btn btn-outline-primary btn-sm" %>
          <%= link_to fa_icon('edit', text: "Modifier"), edit_admin_group_path(@group), class: "btn btn-outline-secondary btn-sm" %>
          <%= link_to fa_icon('trash', text: "Supprimer"), admin_group_path(@group.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-outline-danger btn-sm"%> 
        </td>
      </tr>
    </tbody>  
  </table> 
</div>