config/routes.rb
Rails.application.routes.draw do
 
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  #Devise user
  devise_for :users

  #Routes acces
  root to: "home#index"
  
  #Json fromat routes
  namespace :api do
    namespace :v1 do
      resources :users,       only: [:show]
      resources :payments,    only: [:index]
      resources :groups,      only: [:index]
      resources :settings,    only: [:index]
      resources :promotions,  only: [:index]
    end
   end

  #All ressources pages
  resources :users,       only: [:show]
  resources :payments,    only: [:index]
  resources :groups,      only: [:index]
  resources :settings,    only: [:index]
  resources :promotions,  only: [:index]

  #All ressources admin pages
  namespace :admin do
    resources :users do
      collection do
        post :confirm
      end
    end

    resources :groups do
      collection do
        post :confirm
      end
    end

    resources :promotions do
      collection do
        post :confirm
      end
    end

    resources :payments do
      collection do
        post :confirm
      end
    end

    resources :settings do
      collection do
        post :confirm
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true

  validates :first_name, presence: true

  validates :telephone , presence: true 

  validates :added_since, presence: true

  validates :birthday, presence: true

  validates :profession, presence: true

  belongs_to :promotion

  belongs_to :group

  has_many :payments

  belongs_to :setting
  
  paginates_per 5

  def avatar_thumbnail
    if avatar.present?
      avatar.url
    else
      '/image.png'
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, except: %i[index show]
  before_action :authenticate_admin!

  def index 
    @users = User.all.order('created_at DESC').page params[:page]
  end

  def new
    @group = Group.all
    @user = User.new
  end

  def create
    @group = Group.all
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Utilisateur créé avec succès!"
      redirect_to admin_users_path
    else
      flash[:danger] = "Erreur de création, veuillez réessayer !"
      render :new
    end
  end
  
  def show
    @payment = Payment.all
    @user = User.find(params[:id]) 
  end
  
  def edit
    
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Utilisateur mise à jour avec succès!"
      redirect_to admin_users_path
    else
      if current_user.admin?
        flash[:danger] = 'Veuillez choisir un autre administrateur avant car vous êtes actuellement le seul administrateur.'
        render :new
      else
        flash[:danger] = 'Erreur de mise à jour, veuillez réessayer!'
        render :new
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if (current_user == @user) && (current_user.admin?)
      flash[:danger] = "Vous ne pouvez pas supprimé votre compte"
      redirect_to admin_users_path
    else
      @user.destroy
      flash[:success] = "Utilisateur supprimé"
      redirect_to admin_users_path
    end
  end
  
  private
  def authenticate_admin! 
    unless current_user.admin?
      flash[:info] = "Vous n'avez pas les privilèges pour accéder à cette page."
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :first_name, :email, :avatar, :avatar_cache, :telephone, :added_since, :birthday, :profession, :promotion_id, :group_id, :setting_id, :admin, :password, :password_confirmation)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_user, only:[:show]
  before_action :acces

  def index
    @payments = Payment.all  
    @user = current_user
    render json: @user
    render json: @payments
  end

  def show 
    @user = User.find_by_id(params[:id])
    render json: @user
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
 
  def acces 
    if @user.id != current_user.id 
      redirect_to root_path, notice: "Accès refusé"
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_user, only:[:show]
  before_action :acces

  def index
    @payments = Payment.all  
    @user = current_user
  end

  def show 
    @user = User.find_by_id(params[:id])
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
 
  def acces 
    if @user.id != current_user.id 
      redirect_to root_path, notice: "Accès refusé"
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div id="main"  id="error_explanation">  
  <% if @user.errors.any? %> 
    <div id="error_explanation"  class="alert alert-danger" role="alert"> 
      <h4><%= pluralize(@user.errors.count, "erreurs") %> empêche(nt) <%= @user.name %> d'être sauvegardée(s):</h4> 
      <ul> 
        <% @user.errors.full_messages.each do |message| %> 
          <li><%= message %></li> 
        <% end %> 
      </ul> 
    </div> 
  <% end %> 
  <div class="row"> 
    <div class="col-6 mx-auto"> 
      <%= form_with(model: [:admin, @user], local: true) do |f| %> 
        <div class="form-group">
          <label class="mb-1"><span>Ajouter photo</span></label>
          <%= f.file_field :avatar, autofocus: true, accept:"image/*", autocomplete: "avatar",class:"form-control"%>
          <%= f.hidden_field :avatar_cache %>
        </div>
        
        <div class="field form-goup">
          <%= f.label :Nom %>
          <%= f.text_field :name, :class => 'form-control', autocomplete: 'off'%> 
        </div>

        <div class="field form-goup">
          <%= f.label :Prenom %>
          <%= f.text_field :first_name, :class => 'form-control', autocomplete: 'off' %> 
        </div>

        <div class="field form-goup">
          <%= f.label :Telephone %>
          <%= f.number_field :telephone, :class => 'form-control', autocomplete: 'off' %> 
        </div>

        <div class="field form-goup">
          <%= f.label :Date_ajout %>
          <%= f.date_field :added_since, :class => 'form-control', autocomplete: 'off' %> 
        </div>

        <div class="field form-goup">
          <%= f.label :Email %> 
          <%= f.email_field :email, :class => 'form-control', autocomplete: 'off' %> 
        </div> 

        <div class="field form-goup">
          <%= f.label :Date_d_anniversaire %> 
          <%= f.date_field :birthday, :class => 'form-control' %> 
        </div> 

        <div class="field form-goup">
          <%= f.label :Metier %> 
          <%= f.text_field :profession, :class => 'form-control' %> 
        </div> 

        <div class="field" style="margin-bottom:15px">
          <div class="form-check">
            <%= f.label :Admin, class:"form-check-label", for: "defaultCheck1"%> 
            <%= f.check_box :admin,{}, "true","false"%> 
          </div>
        </div> 
        
        <div class="field" style="margin-bottom:15px">
          <div class="form-group">
            <%= f.label :Groupe %> 
            <%= f.collection_select :group_id, Group.all, :id, :name, {include_blank: "Choisir un groupe.."}, {class: "form-control"}%>
          </div>
        </div> 

        <div class="field" style="margin-bottom:15px"> 
          <div class="form-group">
            <%= f.label :Parametre %> 
            <%= f.collection_select :setting_id, Setting.all, :id, :devise,  {include_blank: "Choisir un paramètre.."}, {class: "form-control"}%>
          </div>
        </div> 

        <div class="field" style="margin-bottom:15px"> 
          <div class="form-group">
            <%= f.label :Promotion %> 
            <%= f.collection_select :promotion_id, Promotion.all, :id, :name,  {include_blank: "Choisir une promotion.."}, {class: "form-control"}%>
          </div>
        </div> 
      
        <div class="field">
          <%= f.label :Mot_det_passe %> 
          <%= f.password_field :password,  :class => 'form-control'  %>
        </div>

        <div class="field">
          <%= f.label :Confirmer_le_mot_de_passe %> 
          <%= f.password_field :password_confirmation, autocomplete: "email",  class: "form-control"  %> 
        </div>
        
        <div class="actions text-center py-2">
          <%= f.submit "Valider", class: "btn btn-secondary btn-sm" %>
          <%= link_to  "Retour", admin_users_path, class: "btn btn-secondary btn-sm" %>
        </div> 
      <% end %> 
    </div> 
</div>

app/views/admin/users/edit.html.erb

<div id="main"  id="error_explanation">  
  <div class="row"> 
    <% if @user.errors.any? %> 
      <div id="error_explanation"  class="alert alert-danger" role="alert"> 
        <h4><%= pluralize(@user.errors.count, "erreurs") %> empêche(nt) <%= @user.name %> d'être sauvegardée(s):</h4> 
        <ul> 
          <% @user.errors.full_messages.each do |message| %> 
            <li><%= message %></li> 
          <% end %> 
        </ul> 
      </div> 
    <% end %>  
    <div class="col-6 mx-auto">
      <h4 class="py-5 fw-normal fs-3 text-uppercase text-center"> Modification</h4>  
      <%= form_with(model: [:admin, @user], local: true) do |f| %> 
        <div class="form-group">
          <label class="mb-1"><span>Add photo</span></label>
          <%= f.file_field :avatar, autofocus: true, accept:"image/*", autocomplete: "avatar",class:"form-control"%>
          <%= f.hidden_field :avatar_cache %>
        </div> 
        <div class="field form-goup">
          <%= f.label :Nom %>
          <%= f.text_field :name, :class => 'form-control', autocomplete: 'off'%> 
        </div> 
        <div class="field form-goup">
          <%= f.label :Prenom %>
          <%= f.text_field :first_name, :class => 'form-control', autocomplete: 'off' %> 
        </div> 
        <div class="field form-goup">
          <%= f.label :Telephone %>
          <%= f.number_field :telephone, :class => 'form-control', autocomplete: 'off' %> 
        </div> 
        <div class="field form-goup">
          <%= f.label :Date_ajout %>
          <%= f.date_field :added_since, :class => 'form-control', autocomplete: 'off' %> 
        </div> 
        <div class="field form-goup">
          <%= f.label :Email %> 
          <%= f.email_field :email, :class => 'form-control', autocomplete: 'off' %> 
        </div>  
        <div class="field form-goup">
          <%= f.label :Date_d_anniversaire %> 
          <%= f.date_field :birthday, :class => 'form-control' %> 
        </div>  
        <div class="field form-goup">
          <%= f.label :Metier %> 
          <%= f.text_field :profession, :class => 'form-control' %> 
        </div>  
        <div class="field" style="margin-bottom:15px">
          <div class="form-check">
            <%= f.label :Admin, class:"form-check-label", for: "defaultCheck1"%> 
            <%= f.check_box :admin,{}, "true","false"%> 
          </div>
        </div>  
        <div class="field" style="margin-bottom:15px">
          <div class="form-group">
            <%= f.label :Groupe %> 
            <%= f.collection_select :group_id, Group.all, :id, :name, {include_blank: "Choisir un groupe.."}, {class: "form-control"}%>
          </div>
        </div>  
        <div class="field" style="margin-bottom:15px"> 
          <div class="form-group">
            <%= f.label :Parametre %> 
            <%= f.collection_select :setting_id, Setting.all, :id, :devise,  {include_blank: "Choisir un paramètre.."}, {class: "form-control"}%>
          </div>
        </div>  
        <div class="field" style="margin-bottom:15px"> 
          <div class="form-group">
            <%= f.label :Promotion %> 
            <%= f.collection_select :promotion_id, Promotion.all, :id, :name,  {include_blank: "Choisir une promotion.."}, {class: "form-control"}%>
          </div>
        </div>  
        <div class="field">
          <%= f.label :Mot_det_passe %> 
          <%= f.password_field :password,  :class => 'form-control'  %>
        </div> 
        <div class="field">
          <%= f.label :Confirmer_le_mot_de_passe %> 
          <%= f.password_field :password_confirmation, autocomplete: "email",  class: "form-control"  %> 
        </div> 
        <div class="actions text-center py-2">
          <%= f.submit "Valider", class: "btn btn-outline-primary btn-sm" %>
          <%= link_to  fa_icon('arrow-left', text: "Retour"), admin_users_path, class: "btn btn-outline-secondary btn-sm" %>
        </div> 
      <% end %>
    </div> 
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container py-4 text-center">
  <div class="row">
      <div class="col-12">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
            <!--<p><%= notice%></p> -->
        <% end %>
      </div>
    </div> 
    <%if current_user.admin%> 
      <div class="row">
        <div class="col-12"> 
          <h5 class="py-4 text-uppercase fw-normal">Vos informations:</h5>
          <table class="table table-borderless">
            <thead class="table-primary">
              <tr class="fs-1 fw-bold">
                <td>Nom</td> 
                <td>Email</td>
                <td>Action</td> 
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= current_user.name%></td>
                <td><%= current_user.email%></td>
                <td>
                  <%= link_to "Acceuil", root_path, :class=>"btn btn-secondary btn-sm"%>
                  <%= link_to "Ajouter utilisateur", new_admin_user_path, :class=>"btn btn-secondary btn-sm"%>
                  <%= link_to "Déconnexion", destroy_user_session_path, method: :delete,:class=>"btn btn-danger btn-sm" %> 
                </td>
              </tr>
            </tbody>
          </table>  
        </div>
      </div> 
    <%end%> 
  <h5 class="mt-11 py-4 text-uppercase fw-normal"> Information de tous les utilisations.</h5>
    <table class="table table-borderless">
      <thead class="table-light">
          <tr class="fs-1 fw-bold">
            <th>Admin</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Telephone</th>
            <th>Nom du groupe</th>
            <th>Email</th>
            <th>Membre Depuis</th>
            <th>Action</th>
          </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.admin %></td>
                <td>
                  <%#= link_to "#{user.name}", admin_user_path(user)%>
                    <button type="button" class="btn btn-primary rounded-pill">
                      <%= link_to "#{user.name}", admin_user_path(user), id: "userName"%> 
                      <span class="badge bg-light text-dark"><%=user.payments.count%></span> 
                    </button>
                </td>
                <td><%= user.first_name%></td>
                <td><%= user.telephone%></td>
                <td>
                  <% if user.group%>
                    <%= user.group.name %>
                  <% end%>
                </td> 
                <td><%= user.email%></td>
                <td><%= user.added_since%></td>
                <td> 
                  <%= link_to fa_icon('see', text: "Afficher"), admin_user_path(user), class: "btn btn-outline-primary btn-sm" %>
                  <%= link_to fa_icon('edit', text: "Modifier"), edit_admin_user_path(user),:class=>"btn btn-outline-secondary btn-sm" %>
                  <%= link_to fa_icon('trash', text: "Supprimer"), admin_user_path(user), method: :delete, data: { confirm: 'are you sure ?' },:class=>"btn btn-outline-danger btn-sm" %>
                </td>
            </tr>
        <% end %>
      </tbody> 
    </table>
  <%= paginate @users%>
</div>

app/views/admin/users/new.html.erb
<div class="container"> 
  <h4 class="py-5 fw-normal fs-3 text-uppercase text-center"> Créer un utilisateur</h4>
</div> 
<%= render 'form'%>

app/views/admin/users/show.html.erb
<div id="main" class="container">
  <!-- Calcul de l'âge-->
  <%age = 0%>
  <%value_age1 = @user.birthday%>
  <%value_age = value_age1.year%>
  <%value_date_now = Date.today.year%>
  <%age = (value_date_now - value_age).to_i%>
  <!-- <p>Votre âge est: <%#= age%></p> -->

  <h3 class="py-3 fs-3 fw-normal text-center">Informations sur l'utilisateur <%=@user.name%></h3>
  <table class="table table-borderless py-3">
    <thead class="table-primary border">
      <tr class="fw-bold fs-1 text-center b-1">
        <th>Image</th> 
        <th>Nom</th> 
        <th>Prénom</th> 
        <th>Téléphone</th>
        <th>Groupe</th> 
        <th>Email</th> 
        <th>La Devise</th>
        <th>Membre Depuis</th>
        <td>Date naissance/Age</td> 
        <td>Age</td>
        <td>Secteur d'activité</td>
        <td>La promotion</td>   
        <th>Action</th>
      </tr>
    </thead> 
    <tbody>
      <tr> 
        <td> 
          <%#= link_to "#{@user.name}", user_path( @user.id)%>
          <%= image_tag @user.avatar_thumbnail, style: "width:60px;height:60px"%>
        </td>
        <td><%= @user.name %></td>
        <td><%= @user.first_name %></td>
        <td><%= @user.telephone %></td>
        <td> 
          <% if @user.group%>
            <%= @user.group.name %>
          <% end%>
        </td>
        <td><%= @user.email %></td>
        <% if @user.setting%>
          <td> 
            <%= @user.setting.devise%>
          </td>
        <%end%> 
        <td><%= @user.added_since %></td> 
        <td><%= @user.birthday %></td>
        <td><%= age %></td>
        <td><%= @user.profession %></td>
        <%if @user.promotion%>
          <td><%= @user.promotion.name %></td>
        <%end%>         
        <td> 
          <%= link_to fa_icon('edit', text: "Modifier"), edit_admin_user_path(@user), class: "btn btn-outline-secondary btn-sm" %>
          <%= link_to fa_icon('trash', text: "Supprimer"), admin_group_path(@user.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-outline-danger btn-sm"%> 
        </td>
      </tr>
    </tbody>  
  </table> 
  <%= link_to fa_icon('plus', text: "Nouveau paiement"), new_admin_payment_path(@user), class: "btn btn-outline-primary btn-sm" %>
  <!--les paiements-->
  <h4 class="fs-3 fw-normal py-5 text-center">Information sur les paiements</h4>  
  <table class="table table-borderless py-3">
    <thead class="table-primary border">
      <tr class="fw-bold fs-1 text-center b-1">
        <th>Date du paiement</th> 
        <th>Note</th> 
        <th>Montant du paiement</th>  
        <!--<th>Action</th>-->
      </tr>
    </thead> 
    <tbody> 
    <% nbre = 0 %>
      <% @payment.each do |payment| %> 
        <tr class="text-center">   
          <% if @user.id == payment.user_id%>         
            <td><%= payment.date_payment %></td>
            <td><%= payment.note %></td>
            <td><%= payment.pay_amount %></td>
           <!-- <td>
              <%#= link_to  "Back", admin_users_path, class: "btn btn-secondary" %> |
              <%#= link_to "Edit", edit_admin_payment_path(user.id), class: "btn btn-secondary" %> 
              <%#= link_to "Delete", admin_group_path(@user.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-secondary"%> 
            </td> -->
            
            <%#= @payment.where(user_id: payment.user_id).count%>
            
            <% if payment.present?%>   
              <% nbre += payment.pay_amount %>
              <% nbre%>
            <%end%>
          <%end%>
        </tr>   
      <%end %> 
    </tbody>  
  </table>
  <p class="text-center py-5">
    Montant total du paiement = <span class="badge bg-success py-2"><%= nbre%>, <%= @user.setting.devise%></span>
    <%if @user.added_since.year < Date.today.year%>
      <% date = (Date.today.year - @user.added_since.year).to_i%>
      <% date = (date + 1)%>
      <% total = (date*@user.setting.amount_due)%>
      <% if total > nbre %>
        <br> 
        Vous devez payez <%= nbre_total = (total - nbre)%>, <%= @user.setting.devise%>
      <% elsif total < nbre%>
        <p>Vous êtes dans les normes. Votre surplus est de<%= nbre_total = nbre - total%>, <%= @user.setting.devise%></p>
          <%year = (nbre_total.to_f / @user.setting.amount_due.to_f).to_f %>
          <%= year.to_i%> , year(s)
          <% recup_val_month = year - year.to_i%>
          <% month = (recup_val_month.to_f * 12)%>
          <%= month.to_i%>, month(s)
      <%else%>
        <p>Vous êtes dans les normes.</p>
      <%end%>
    <% elsif  @user.added_since.year > Date.today.year%>
      ...
    <%else%> 
      <!--
        You must pay <%#= total = (nbre - @user.setting.amount_due)%>, <%#= @user.setting.devise%>
      -->
      <% date = (Date.today.year - @user.added_since.year).to_i%>
      <% date = (date + 1)%>
      <% total = (date*@user.setting.amount_due)%>
      <% if total > nbre %>
        <br> 
        Vous devez payez <%= nbre_total = (total - nbre)%>, <%= @user.setting.devise%>
      <% elsif total < nbre%>
        <p class="text-center">Vous êtes dans les normes. Votre surplus est de <%= nbre_total = nbre - total%>, <%= @user.setting.devise%></p>
          <%year = (nbre_total.to_f / @user.setting.amount_due.to_f).to_f %>
        <p class="text-center"><%= year.to_i%> , year(s)
          <% recup_val_month = year - year.to_i%>
          <% month = (recup_val_month.to_f * 12)%>
          <%= month.to_i%>, month(s)
        </p>
      <%else%>
        <p class="text-center">Vous êtes dans les normes.</p>
      <%end%> 
    <%end%> 
  </p>
</div>